apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: falco
  namespace: falco
spec:
  mode: daemonset
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane

  config:
    receivers:
      filelog:
        include_file_path: true
        include:
          - /var/log/pods/falco_falco*/falco/*.log
        operators:
          - id: container-parser
            type: container
          - type: json_parser
            parse_from: body
            parse_to: attributes.falco

    exporters:
      otlp:
        endpoint: "api.honeycomb.io:443" # US instance
        headers:
          "x-honeycomb-team": "${OTEL_HONEYCOMB_APIKEY}"
          "x-honeycomb-dataset": "falco"
    service:
      pipelines:
        logs:
          receivers: [filelog]
          exporters: [otlp]
  env:
    - name: OTEL_HONEYCOMB_APIKEY
      valueFrom:
        secretKeyRef:
          name: otel-honeycomb-apikey
          key: apikey

  volumeMounts:
    - name: pod-logs
      mountPath: /var/log/pods
  volumes:
    - name: pod-logs
      hostPath:
        path: /var/log/pods